### ISSUE TITLE
Intallation

### ISSUE THREAD

**Issue by siparast** [scottclowe/matlab-schemer#17]
Can someone tell me exactly what to do. I can't get it to work

**Comment by scottclowe** [comment]
1. Download zip file either [through github](https://github.com/scottclowe/matlab-schemer/archive/master.zip) or [through fileexchange](https://mathworks.com/matlabcentral/fileexchange/53862-matlab-schemer).
2. Extract the zip file contents to whatever folder you'd like to put the files in.
3. Run MATLAB.
4. Add the matlab-schemer folder to your MATLAB path, so MATLAB will be able to find the file `schemer_import.m`. There's various ways you can do this.
4a. You can do this by clicking the `'Set path'` button on the MATLAB tool ribbon, then use `'Add folder'` or `'Add with subfolders'` and select the matlab-schemer folder (for Schemer, you don't need to add subfolders, but for other packages you do).
4b. Or you can use `addpath` command [(doc)](https://mathworks.com/help/matlab/ref/addpath.html).
4c. Or you can change the current folder in MATLAB, either using [`cd`](https://mathworks.com/help/matlab/ref/cd.html) or the GUI, to be the directory containing MATLAB schemer. This will work because the current folder is always included in the search path, but it is only temporary because MATLAB Schemer will stop being on the path when you move to a different folder.
5. Type  `schemer_import` at the MATLAB command prompt.

**Comment by siparast** [comment]
Thanks a lot!

**Comment by scottclowe** [comment]
I take it everything is working now? Let me know if you have any issues.

**Comment by siparast** [comment]
Yeah everything is working now. I had to reinstall my matlab for some reason but after that everything worked out great.
Appreciate the help
