### ISSUE TITLE
Using Octave, not working.

### ISSUE THREAD

**Issue by billchenxi** [scottclowe/matlab-schemer#18]
It reported this error:
'com' undefined near line 537 column 17
error: called from
    schemer_import>main at line 537 column 17
    schemer_import at line 176 column 26

please help, thanks,

**Comment by scottclowe** [comment]
This package is just for changing the colour scheme in MATLAB. Octave is not supported and is not intended to be.

It is true that setting a colour scheme in Octave is just as cumbersome as it is in MATLAB (without using the MATLAB Schemer package). However, I don't think that integrating an Octave colour scheme manager and a MATLAB colour scheme manager together into the same package is the solution. Due to differences in the underlying code of MATLAB and Octave, a solution for Octave would effectively require a complete rewrite of MATLAB Schemer. Furthermore, MATLAB and Octave have different syntax highlighting options (Octave has more font customisation and background colours; both have a few syntactic items the other does not; each has a different set of additional languages supported) which makes the creation of a unified style sheet problematic.

There is a [feature request to add a colour scheme manager to Octave](http://savannah.gnu.org/bugs/?48630), and I recommend you voice your support for this there. Since Octave is open source, the community can create a solution which is fully integrated into the Octave core (unlike for MATLAB, where MATLAB Schemer is a third-party solution using undocumented MATLAB features which may be changed or removed future versions without notice).

I know it is tedious, but in the meantime you can still customise the Octave colour scheme manually by opening the preferences pane and changing the settings of the "Editor Styles" panel.
