### ISSUE TITLE
can't view your png files on GitHub

### ISSUE THREAD

**Issue by brianpenghe** [scottclowe/matlab-schemer#19]
Hi, somehow I'm not able to view your .png files on GitHub. Do you know why?

**Comment by scottclowe** [comment]
Hi @brianpenghe. I do not know why, since they work for me. I also tested loading them with JavaScrpt disabled, and GitHub still rendered the PNG files unimpeded.

If you [go here](https://github.com/scottclowe/matlab-schemer/blob/master/schemes/screenshots/solarized-light.png), you should see a screenshot of the Solarized colour scheme.

As a cross-repository test, [going here](https://github.com/github-tools/github/blob/master/test/fixtures/gh.png) should show you a GitHub logo (octocat) as a png.

Do either of these work for you?

**Comment by brianpenghe** [comment]
Yes both worked on my Firefox browser. Somehow my Chrome doesn't show them : (
