### ISSUE TITLE
Matlab r2017a Programming Tools Preferences

### ISSUE THREAD

**Issue by planetrocky** [scottclowe/matlab-schemer#20]
At least these variables don't seem to exist in r2017a anymore:
ColorsUseMLintAutoFixBackground
Editor.VariableHighlighting.Automatic
Editor.NonlocalVariableHighlighting
EditorCodepadHighVisible
EditorCodeBlockDividers
Editorhighlight-caret-row-boolean

**Comment by scottclowe** [comment]
Hi @planetrocky, why do you say this? Why do you think these settings no longer exist?

**Comment by planetrocky** [comment]
None of those variables exist in my r2017a, so import/export doesn't work for those settings

**Comment by planetrocky** [comment]
Ok, I've done more testing.

I can only get these variables to appear when toggling on/off within the Matlab GUI preferences. Prior to that they never existed and would not be import/export their state with the scripts here.

**Comment by scottclowe** [comment]
Ah yes, that's right. The variables don't appear in matlab.prf until after you have visited the preference pane where the variable is set and clicked Okay (not Cancel) to leave the preferences menu.

This is why you have to visit each pane and click okay before you export, otherwise you will get out black for all the unset colours. This is mentioned in the [Export section of the README](https://github.com/scottclowe/matlab-schemer#exporting-through-the-gui), and [in the help documentation for `schemer_export`](https://github.com/scottclowe/matlab-schemer/blob/master/schemer_export.m#L76) with a note [at the first line of the documentation](https://github.com/scottclowe/matlab-schemer/blob/master/schemer_export.m#L2).

I realise its not intuitive that you have to visit the panes to initialise the output, but unfortunately its not something I can do anything about. If you think I can change the documentation in someway so this is more apparent please let me know.
