### ISSUE TITLE
Live Script  is not affected by theme changes

### ISSUE THREAD

**Issue by wbadry** [scottclowe/matlab-schemer#22]
Hello,
I hope schemer could affect live script as well.

**Comment by scottclowe** [comment]
Unfortunately, Matlab Live Scripts do not currently support customisation of colour schemes. Since it is not possible for the user to manually change the colours, it is not possible for `matlab-schemer` to change the colours either.

In the [documentation for Live Script](https://www.mathworks.com/help/matlab/matlab_prog/what-is-a-live-script-or-function.html#bvg6yjm-4), MathWorks says this point of note:

> **Unsupported Features**
> When deciding whether to create a live script or function, it is important to note several unsupported features in the Live Editor:
> - ...
> - Editor preferences — The Live Editor ignores most Editor preferences, including custom keyboard shortcuts and Emacs-style keyboard shortcuts.

If it becomes possible to change the colour palette of Live Script in the future, I'll happily add support for it then.
